### ISSUE TITLE
Can you add git tags for ExDoc?

### ISSUE THREAD

**Issue by petermueller** [subvisual/fsmx#15]
When looking at the `</>` buttons on hexdocs.pm, or any documentation tool (e.g. "Dash", or "Zeal"), `ex_doc` attempts to use the library version to construct a link, and assumes there's an equivalent git tag.

Could you push some git tags matching those versions so I can more easily review things when implementing? Main example is from when I need a reminder of what the `use Fsmx.Fsm` does.

If there's another way you'd prefer that's fine too. I'd submit a PR, but tags aren't PR-able, and anything else would probably be something you'd wanna discuss first 😅

**Comment by naps62** [comment]
uh. that's an odd assumption from those tools 😅 
I just tagged the commit for the latest release ([0.4.1](https://github.com/subvisual/fsmx/releases/tag/0.4.1)) can you let me know if that worked?

Also, do you need me to do this for previous versions as well?

**Comment by petermueller** [comment]
hmm, it does not.

I'm trying to find `ex_doc`'s documentation on configuring for how the "source" (`</>`) buttons work, but it doesn't have something I can find quickly.

Oh, the link it generates is `https://github.com/subvisual/fsmx/blob/v0.4.1/lib/fsmx/fsm.ex#L1`, so I think maybe if you push a tag of `v0.4.1` it'll work.

I wish this was better documented
I think the EEF just started a working group for library maintainers that might result in some better commands/defaults for libraries, so this stuff is just sorta built-in when pushing a release

Thank you so much for the prompt response btw ❤️

**Comment by petermueller** [comment]
Oh and to your question: _I_ don't need it for previous releases, but it wouldn't hurt? idk. I don't know what the usage is of previous versions, or if hex.pm surfaces that :-/

**Comment by naps62** [comment]
@petermueller `v0.4.1` pushed. if that works I can push for some of the previous releases

**Comment by petermueller** [comment]
Works! Beautiful! Thank you ❤️ 💖
