### ISSUE TITLE
Implementation for `transition_changeset/4` required for all transitions since 0.5.0?

### ISSUE THREAD

**Issue by linusdm** [subvisual/fsmx#17]
There seems to be a change since version 0.5.0 that's breaking when there is no callback defined for a valid `transition_changeset/4` callback. Previously the implementation of this callback was optional.

The documentation for `before_transition/3` mentions this:
> You only need to pattern-match on the scenarios you want to catch. No need to add a catch-all/do-nothing function at the end (the library already does that for you).

This also applied to the `transition_changeset/4` callback before, but that has changed, resulting in a `FunctionClauseError` error when a valid transition is triggered.

I'm curious if this is intended. It's trivial to supply a default implementation for this callback, but I actually preferred the previous behaviour.

See this livebook for a reproduction (use the import functionality, choose "From URL", and paste this url):
https://gist.github.com/linusdm/a79c241c2f9b7a1c3ac158b1aa530ca2#file-repro-livemd

Thanks in advance for any feedback!

**Comment by naps62** [comment]
@linusdm I think this was an oversight in the latest changes. We added an extra field, but forgot to set the default in the catch-all case (so only `transition_changeset/5` was caught, not `transition_changeset/4`)

I opened #18 , but I think I'll have to wait for @zamith to come back to double check. (I'm on the road and with no good ability to properly test this)
in the meantime, if you can try that branch and confirm if it fixes your scenario, that would be a huge help!

And thanks for reporting

**Comment by linusdm** [comment]
Whoa, that was quick :) 

It works with the changes from the branch you mentioned! No worries regarding timing.

Thanks for taking the time and the fix, appreciate it!
